server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_sum?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:formate_sql: true